"""
Django settings for ihike_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from BASE_DIR/.env if present
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    'django-insecure-sp!10%v5(xvymaw-z^99qymw=u+___3k7^rd7#&&-c8y9*e5+2',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv(
        "ALLOWED_HOSTS",
        "ihike-api-dev.eba-dpt4em9m.us-east-1.elasticbeanstalk.com,localhost,127.0.0.1",
    ).split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'rest_framework_gis',
    'django_filters',
    'corsheaders',
    'hiking',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ihike_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ihike_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_name = os.getenv("DB_NAME")
_database_url = os.getenv("DATABASE_URL")

_db_parsed = None
if _database_url and _database_url.strip():
    try:
        _db_parsed = dj_database_url.parse(
            _database_url.strip(),
            conn_max_age=600,
            ssl_require=os.getenv('DB_SSLMODE', '').lower() == 'require',
        )
    except Exception:
        _db_parsed = None

if _db_parsed:
    DATABASES = {'default': _db_parsed}
    engine = DATABASES['default'].get('ENGINE')
    if engine in (
        'django.db.backends.postgresql',
        'django.db.backends.postgresql_psycopg2',
    ):
        DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'
    
    # Don't force IPv4 resolution - let psycopg2 handle it naturally
    # This is important for services like Supabase that use connection poolers
    # which may require the hostname for SSL/TLS SNI
elif _db_name:
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': _db_name,
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {k: v for k, v in {
                'sslmode': os.getenv('DB_SSLMODE', None),
            }.items() if v},
        }
    }
    # Don't force IPv4 - let the connection library handle it
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Database connection note:
# We don't force IPv4 resolution anymore because:
# 1. Supabase pooler requires hostname for SSL/TLS SNI
# 2. Modern AWS instances handle IPv4/IPv6 automatically
# 3. psycopg2 handles connection details correctly when given proper DATABASE_URL


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# GDAL/GEOS native library paths (Windows)
# Set these in your .env if needed, e.g.:
# GDAL_LIBRARY_PATH=C:\\OSGeo4W\\bin\\gdal312.dll
# GEOS_LIBRARY_PATH=C:\\OSGeo4W\\bin\\geos_c.dll
# Optionally, set GDAL_BIN_DIR or OSGEO4W_ROOT to help the loader find DLLs

# GeoDjango Library Configuration
# Point to system libraries or use Shapely's bundled GEOS as fallback
GDAL_LIBRARY_PATH = os.getenv('GDAL_LIBRARY_PATH')
GEOS_LIBRARY_PATH = os.getenv('GEOS_LIBRARY_PATH')

# On Windows or if system libs not available, try Shapely's bundled GEOS
if not GEOS_LIBRARY_PATH or not os.path.exists(str(GEOS_LIBRARY_PATH)):
    try:
        import shapely
        _shapely_dir = os.path.dirname(shapely.__file__)
        _libs_dir = os.path.join(_shapely_dir, '.libs')
        
        if os.path.exists(_libs_dir):
            _geos_files = [f for f in os.listdir(_libs_dir) if 'geos_c' in f]
            if _geos_files:
                GEOS_LIBRARY_PATH = os.path.join(_libs_dir, _geos_files[0])
    except Exception:
        pass

# REST framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework_gis.filters.InBBoxFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Use default JSON renderer; GeoFeatureModelSerializer in serializers
    # will produce valid GeoJSON (geometry objects) without a special renderer.
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] + (['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else []),
    'DEFAULT_PAGINATION_CLASS': 'ihike_backend.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': int(os.getenv('API_PAGE_SIZE', '200')),
    'COERCE_DECIMAL_TO_STRING': False,
}

# CORS
CORS_ALLOWED_ORIGINS = [
    *[o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()],
]
CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'false').lower() in ('1', 'true', 'yes', 'on')

# If no specific origins are set, allow all in development when DEBUG is true
if DEBUG and not CORS_ALLOWED_ORIGINS:
    CORS_ALLOW_ALL_ORIGINS = True