# Generated by Django 5.2.7 on 2025-10-11 06:32

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hiking", "0003_add_filter_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="path",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["geometry"], name="path_geometry_gix"
            ),
        ),
        migrations.AddIndex(
            model_name="trail",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["geometry"], name="trail_geometry_gix"
            ),
        ),
    ]
